### ISSUE TITLE
ConceptsTest & Concepts classes obsolete

### ISSUE THREAD

**Issue by randykerber** [egonw/ops4j#9]
Since ConceptWiki is history, doesn't make sense to keep testing the ConceptsTest test cases.

Disable them? Delete them? Adapt to Ian's new ops-search based commands?

**Comment by egonw** [comment]
@randykerber what are the new (replacing) Open PHACTS API methods?

**Comment by randykerber** [comment]
@egonw -- not sure. We should check with Ian (@ianwdunlop).

**Comment by randykerber** [comment]
Ian hasn't created test cases yet.

Here's test case 0:  http://alpha.openphacts.org:3002/search?query=aspirin

The latest swagger file is here:
   https://github.com/openphacts/OPS_LinkedDataApi/blob/alpha-2.2/api-config-files/swagger-2.2.json

I'm not really familiar with swagger, but "/search" is the first entry, can see what the current/planned query parameters are.  `&limit=1` probably useful for testing.
